[project]
name = "past-paper-notes-flashcard-generator"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "linkify-it-py>=2.1.0",
    "markdown-it-py>=4.0.0",
    "mdit-py-plugins>=0.5.0",
    "requests>=2.33.1",
    "toml>=0.10.2",
]

[project.scripts]
convert-exam-notes = "convert_exam_notes.main:main"
